batch_size: 20480
ckpt_path: null
dataset_name: colmap
distortion_loss_w: 0
downsample: 0.25
eval_lpips: false
exp_name: fern
lr: 0.02
no_save_test: false
num_epochs: 30
num_gpus: 1
optimize_ext: false
random_bg: false
ray_sampling_strategy: deferred_images
root_dir: /home/wenri/Projects/NeRF_Data/nerf_llff_data/fern
scale: 2.0
split: train
use_exposure: false
val_only: false
weight_path: null
